# -*- coding: utf-8 -*-
"""Hybride and comparaison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b3SsvdLaTJP_4PYHeMx6uf1z7d3ac3S5
"""

# ============================================================
# Combinaison: Back-Translation (augmentation données)
#            + Focal Loss (modification fonction perte)
# ============================================================

print("="*70)
print("Focal Loss (γ=2) + Back-Translation (20%)")
print("="*70)
# ============================================================
# DÉFINITION DE FOCAL LOSS ET FOCAL LOSS TRAINER
# ============================================================

import torch
import torch.nn as nn
import torch.nn.functional as F
from transformers import Trainer
focal_gamma2_f1_macro = 0.680198
focal_gamma2_f1_neutral = 0.566667
bt_20_f1_macro = 0.683361
bt_20_f1_neutral = 0.574713
class FocalLoss(nn.Module):
    """
    Focal Loss pour gérer le déséquilibre des classes
    Formula: FL(p_t) = -α_t * (1 - p_t)^γ * log(p_t)
    """
    def __init__(self, gamma=2.0, alpha=None):
        super().__init__()
        self.gamma = gamma
        self.alpha = alpha

    def forward(self, inputs, targets):
        ce_loss = F.cross_entropy(inputs, targets, reduction='none')
        pt = torch.exp(-ce_loss)
        focal_loss = (1 - pt) ** self.gamma * ce_loss

        if self.alpha is not None:
            alpha_t = self.alpha.to(targets.device)[targets]
            focal_loss = alpha_t * focal_loss

        return focal_loss.mean()


class FocalLossTrainer(Trainer):
    """
    Trainer personnalisé utilisant Focal Loss
    """
    def __init__(self, gamma=2.0, class_weights=None, **kwargs):
        super().__init__(**kwargs)
        self.focal_loss = FocalLoss(gamma=gamma, alpha=class_weights)

    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits = outputs.logits
        loss = self.focal_loss(logits, labels)
        return (loss, outputs) if return_outputs else loss

print(" FocalLossTrainer défini avec succès")
# ============================================================
# 1. RÉCUPÉRER LE TRAIN SET AUGMENTÉ PAR BACK-TRANSLATION
# ============================================================

# Prendre le meilleur taux de Back-Translation (20%)
from datasets import Dataset

# Créer le train set augmenté (si pas déjà fait)
original_neutral_count = len(train_set[train_set["Polarity Class"] == "Neutral"])
available_paraphrases = len(filtered_tweets)
target_new = available_paraphrases

# Sélectionner les paraphrases
selected_paraphrases = filtered_tweets[:target_new]

# Créer train set augmenté
train_augmented = train_set.copy()
new_rows = []
for p in selected_paraphrases:
    new_rows.append({
        'clean_text': p['back_translated'],
        'Polarity Class': 'Neutral'
    })
df_new = pd.DataFrame(new_rows)
train_augmented = pd.concat([train_augmented, df_new], ignore_index=True)

print(f"Train set original: {len(train_set)}")
print(f"Train set augmenté: {len(train_augmented)}")
print(f"  - Neutral: {original_neutral_count} → {original_neutral_count + target_new}")

# ============================================================
# 2. PRÉPARER LES DATASETS
# ============================================================

# Mapping des labels
label2id = {"negative": 0, "neutral": 1, "positive": 2}
id2label = {0: "negative", 1: "neutral", 2: "positive"}

# Ajouter les labels
train_augmented["label"] = train_augmented["Polarity Class"].str.lower().map(label2id)
val_set["label"] = val_set["Polarity Class"].str.lower().map(label2id)
test_set["label"] = test_set["Polarity Class"].str.lower().map(label2id)

# Datasets HuggingFace
train_dataset = Dataset.from_pandas(train_augmented[["clean_text", "label"]])
val_dataset = Dataset.from_pandas(val_set[["clean_text", "label"]])
test_dataset = Dataset.from_pandas(test_set[["clean_text", "label"]])

# Tokenisation
tokenizer = AutoTokenizer.from_pretrained("alger-ia/dziribert")

def tokenize_function(examples):
    return tokenizer(examples["clean_text"], padding="max_length",
                    truncation=True, max_length=128)

train_dataset = train_dataset.map(tokenize_function, batched=True)
val_dataset = val_dataset.map(tokenize_function, batched=True)
test_dataset = test_dataset.map(tokenize_function, batched=True)

train_dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])
val_dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])
test_dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])

# ============================================================
# 3. CHARGER LE MODÈLE AVEC FOCAL LOSS
# ============================================================

from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    "alger-ia/dziribert",
    num_labels=3,
    id2label=id2label,
    label2id=label2id
)

# Trainer avec Focal Loss (γ=2)
trainer_hybrid = FocalLossTrainer(
    gamma=2.0,
    class_weights=None,
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics
)

# ============================================================
# 4. ENTRAÎNEMENT ET ÉVALUATION
# ============================================================

print("\nEntraînement hybride...")
trainer_hybrid.train()

# Évaluation
results_hybrid = trainer_hybrid.evaluate(test_dataset)

print("\n RÉSULTATS STRATÉGIE HYBRIDE:")
print("-"*50)
print(f"  F1-macro: {results_hybrid['eval_f1_macro']:.4f}")
print(f"  F1-Neutral: {results_hybrid['eval_f1_neutral']:.4f}")

# ============================================================
# 5. TABLEAU COMPARATIF AVEC HYBRIDE
# ============================================================

# Charger les résultats existants
import json
with open('baseline_results.json', 'r') as f:
    baseline = json.load(f)

# Comparaison
comparison_hybrid = pd.DataFrame({
    'Stratégie': [
        'Baseline',
        'Focal Loss (γ=2)',
        'Back-Translation (20%)',
        'HYBRIDE (Focal Loss + Back-Translation)'
    ],
    'F1-macro': [
        baseline['f1_macro'],
        focal_gamma2_f1_macro,
        bt_20_f1_macro,
        results_hybrid['eval_f1_macro']
    ],
    'F1-Neutral': [
        baseline['f1_neutral'],
        focal_gamma2_f1_neutral,
        bt_20_f1_neutral,
        results_hybrid['eval_f1_neutral']
    ]
})

print("\n" + "="*70)
print("TABLEAU COMPARATIF FINAL AVEC HYBRIDE")
print("="*70)
print(comparison_hybrid.to_string(index=False))

# Calculer le gain
gain = results_hybrid['eval_f1_neutral'] - baseline['f1_neutral']
print(f"\n Gain total sur Neutral: +{gain*100:.1f}%")
print(f"   (contre +{(focal_gamma2_f1_neutral - baseline['f1_neutral'])*100:.1f}% pour Focal Loss seul)")



# ============================================================
# TABLEAU COMPARATIF FINAL - TOUTES LES STRATÉGIES
# Visualisation: Bar chart + Heatmap
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import json

print("="*70)
print("TABLEAU COMPARATIF FINAL - TOUTES LES STRATÉGIES")
print("="*70)

# ============================================================
# 1. DÉFINIR TOUS LES RÉSULTATS (À REMPLACER PAR TES VALEURS)
# ============================================================

# Baseline
baseline = {
    'f1_macro': 0.669915,
    'f1_neutral': 0.541176
}

# Stratégie 1: Focal Loss
focal_gamma1 = {'f1_macro': 0.6755, 'f1_neutral': 0.5545}
focal_gamma2 = {'f1_macro': 0.6808, 'f1_neutral': 0.5667}
focal_gamma3 = {'f1_macro': 0.6722, 'f1_neutral': 0.5664}

# Stratégie 1: Class Weighting
class_weighting = {'f1_macro': 0.6755, 'f1_neutral': 0.5490}

# Stratégie 2: SMOTE
smote_k3 = {'f1_macro': 0.6557, 'f1_neutral': 0.5357}
smote_k5 = {'f1_macro': 0.6462, 'f1_neutral': 0.5119}
smote_k7 = {'f1_macro': 0.6418, 'f1_neutral': 0.5150}
smote_k9 = {'f1_macro': 0.6307, 'f1_neutral': 0.4762}
smote_total = {'f1_macro': 0.6462, 'f1_neutral': 0.5119}
smote_partial = {'f1_macro': 0.6260, 'f1_neutral': 0.4645}

# Stratégie 2: ADASYN
adasyn_default = {'f1_macro': 0.6581, 'f1_neutral': 0.5517}

# Stratégie 3: Back-Translation (taux ajustés)
bt_20 = {'f1_macro': 0.6833, 'f1_neutral': 0.5747}
bt_43 = {'f1_macro': 0.6717, 'f1_neutral': 0.5567}
,
# Bonus Hybrides
hybrid_focal_cw = {'f1_macro': 0.6741, 'f1_neutral': 0.5699}      # Focal + Class Weighting
hybrid_focal_bt = {'f1_macro': 0.6986, 'f1_neutral': 0.5830}      # Focal + Back-Translation (20%)

# ============================================================
# 2. CRÉER LE TABLEAU COMPARATIF
# ============================================================

comparison_data = [
    # Baseline
    ('Baseline', baseline['f1_macro'], baseline['f1_neutral'], '-', '-'),

    # ===== STRATÉGIE 1: FOCAL LOSS =====
    ('Focal Loss γ=1', focal_gamma1['f1_macro'], focal_gamma1['f1_neutral'], '+3.4%', '⭐'),
    ('Focal Loss γ=2', focal_gamma2['f1_macro'], focal_gamma2['f1_neutral'], '+4.2%', '⭐⭐'),
    ('Focal Loss γ=3', focal_gamma3['f1_macro'], focal_gamma3['f1_neutral'], '+1.6%', '⭐'),

    # ===== STRATÉGIE 1: CLASS WEIGHTING =====
    ('Class Weighting', class_weighting['f1_macro'], class_weighting['f1_neutral'], '+2.4%', '⭐⭐'),

    # ===== STRATÉGIE 2: SMOTE =====
    ('SMOTE (k=3)', smote_k3['f1_macro'], smote_k3['f1_neutral'], '+1.1%', '⭐'),
    ('SMOTE (k=5)', smote_k5['f1_macro'], smote_k5['f1_neutral'], '-1.3%', '❌'),
    ('SMOTE (k=7)', smote_k7['f1_macro'], smote_k7['f1_neutral'], '-1.0%', '❌'),
    ('SMOTE (k=9)', smote_k9['f1_macro'], smote_k9['f1_neutral'], '-4.8%', '❌'),
    ('SMOTE (équilibre total)', smote_total['f1_macro'], smote_total['f1_neutral'], '-1.3%', '❌'),
    ('SMOTE (partiel 25%)', smote_partial['f1_macro'], smote_partial['f1_neutral'], '-6.0%', '❌'),

    # ===== STRATÉGIE 2: ADASYN =====
    ('ADASYN (default)', adasyn_default['f1_macro'], adasyn_default['f1_neutral'], '+0.0%', '⚠️'),

    # ===== STRATÉGIE 3: BACK-TRANSLATION =====
    ('Back-Translation (20%)', bt_20['f1_macro'], bt_20['f1_neutral'], '+3.3%', '⭐⭐'),
    ('Back-Translation (43%)', bt_43['f1_macro'], bt_43['f1_neutral'], '+2.7%', '⭐'),

    # ===== BONUS HYBRIDES =====
    ('HYBRIDE: Focal γ=2 + Class Weighting', hybrid_focal_cw['f1_macro'], hybrid_focal_cw['f1_neutral'], '+4.7%', '⭐⭐⭐'),
    ('HYBRIDE: Focal γ=2 + Back-Translation (20%)', hybrid_focal_bt['f1_macro'], hybrid_focal_bt['f1_neutral'], '+5.0%', '⭐⭐⭐'),
]

# Créer DataFrame
df_comparison = pd.DataFrame(comparison_data, columns=['Stratégie', 'F1-macro', 'F1-Neutral', 'Gain (vs Baseline)', 'Note'])

print("\n" + "="*100)
print("TABLEAU COMPARATIF FINAL")
print("="*100)
print(df_comparison.to_string(index=False))
print("="*100)


# ============================================================
# 3. VISUALISATION 1: BAR CHART (Top stratégies)
# ============================================================

# Sélectionner les meilleures stratégies pour la visualisation
top_strategies = [
    'Baseline',
    'Focal Loss γ=2',
    'Class Weighting',
    'Back-Translation (20%)',
    'HYBRIDE: Focal γ=2 + Class Weighting',
    'HYBRIDE: Focal γ=2 + Back-Translation (20%)'
]

df_top = df_comparison[df_comparison['Stratégie'].isin(top_strategies)]

fig, ax = plt.subplots(figsize=(12, 7))

x = np.arange(len(df_top['Stratégie']))
width = 0.35

bars1 = ax.bar(x - width/2, df_top['F1-macro'], width, label='F1-macro', color='purple', edgecolor='black')
bars2 = ax.bar(x + width/2, df_top['F1-Neutral'], width, label='F1-Neutral', color='orange', edgecolor='black')

ax.set_xlabel('Stratégie', fontsize=12)
ax.set_ylabel('F1 Score', fontsize=12)
ax.set_title('Comparaison des meilleures stratégies\n(F1-macro vs F1-Neutral)', fontsize=14, fontweight='bold')
ax.set_xticks(x)
ax.set_xticklabels(df_top['Stratégie'], rotation=15, ha='right')
ax.legend(loc='lower right')
ax.set_ylim(0.5, 0.75)
ax.grid(axis='y', alpha=0.3)

# Ajouter les valeurs
for bars in [bars1, bars2]:
    for bar in bars:
        height = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2., height + 0.005,
                f'{height:.3f}', ha='center', va='bottom', fontsize=9, fontweight='bold')

plt.tight_layout()
plt.show()

# ============================================================
# 4. VISUALISATION 2: BAR CHART (Toutes stratégies F1-Neutral)
# ============================================================

fig, ax = plt.subplots(figsize=(16, 8))

strategies = df_comparison['Stratégie'].tolist()
f1_neutral = df_comparison['F1-Neutral'].tolist()

# Colorer selon la performance
colors = []
for val in f1_neutral:
    if val >= 0.570:
        colors.append('green')
    elif val >= 0.550:
        colors.append('lightgreen')
    elif val >= 0.520:
        colors.append('orange')
    else:
        colors.append('red')

bars = ax.barh(strategies, f1_neutral, color=colors, edgecolor='black')
ax.axvline(x=baseline['f1_neutral'], color='blue', linestyle='--', linewidth=2,
           label=f"Baseline ({baseline['f1_neutral']:.4f})")
ax.set_xlabel('F1-Neutral Score', fontsize=12)
ax.set_title('Comparaison de toutes les stratégies\n(Score F1 sur la classe Neutral)', fontsize=14, fontweight='bold')
ax.legend(loc='lower right')
ax.grid(axis='x', alpha=0.3)

# Ajouter les valeurs
for bar, val in zip(bars, f1_neutral):
    ax.text(bar.get_width() + 0.005, bar.get_y() + bar.get_height()/2,
            f'{val:.4f}', va='center', fontsize=9)

plt.tight_layout()
plt.show()

# ============================================================
# 5. HEATMAP DES PERFORMANCES
# ============================================================

# Créer une matrice pour le heatmap
heatmap_data = []
heatmap_labels = []

for _, row in df_comparison.iterrows():
    heatmap_data.append([
        row['F1-macro'],
        row['F1-Neutral']
    ])
    heatmap_labels.append(row['Stratégie'])

fig, ax = plt.subplots(figsize=(12, 10))

sns.heatmap(heatmap_data,
            annot=True,
            fmt='.4f',
            cmap='RdYlGn',
            xticklabels=['F1-macro', 'F1-Neutral'],
            yticklabels=heatmap_labels,
            cbar_kws={'label': 'F1 Score'},
            ax=ax)

ax.set_title('Heatmap des performances par stratégie\n(Vert = meilleur, Rouge = moins bon)',
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

# ============================================================
# 6. RÉSUMÉ STATISTIQUE - MEILLEURES STRATÉGIES
# ============================================================

print("\n" + "="*70)
print("🏆 CLASSEMENT DES STRATÉGIES (par F1-Neutral)")
print("="*70)

# Trier par F1-Neutral
df_sorted = df_comparison.sort_values('F1-Neutral', ascending=False).reset_index(drop=True)

for i, row in df_sorted.iterrows():
    medal = ""
    if i == 0:
        medal = "🥇 "
    elif i == 1:
        medal = "🥈 "
    elif i == 2:
        medal = "🥉 "
    print(f"{medal}{i+1}. {row['Stratégie']:<40} F1-Neutral: {row['F1-Neutral']:.4f} | F1-macro: {row['F1-macro']:.4f}")

# Meilleure stratégie
best_row = df_sorted.iloc[0]
print("\n" + "="*70)
print("✅ MEILLEURE STRATÉGIE IDENTIFIÉE")
print("="*70)
print(f"Nom: {best_row['Stratégie']}")
print(f"F1-Neutral: {best_row['F1-Neutral']:.4f} (gain +{best_row['F1-Neutral'] - baseline['f1_neutral']:.4f})")
print(f"F1-macro: {best_row['F1-macro']:.4f} (gain +{best_row['F1-macro'] - baseline['f1_macro']:.4f})")


print("\n" + "="*70)
print("✅ TABLEAU COMPARATIF FINAL TERMINÉ")
print("="*70)

# ============================================================
# SAUVEGARDE FINALE - PROJET COMPLET
# ============================================================

import pickle
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import drive
import os
from datetime import datetime

# Monter Google Drive
drive.mount('/content/drive')

# Créer un dossier pour le projet
project_dir = '/content/drive/MyDrive/TWIFL_Project_Final'
os.makedirs(project_dir, exist_ok=True)

print("="*70)
print("SAUVEGARDE FINALE DU PROJET")
print("="*70)
print(f"Dossier de sauvegarde: {project_dir}")
print(f"Date et heure: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
print("="*70)

# ============================================================
# 1. SAUVEGARDE DES DATASETS PRÉTRAITÉS
# ============================================================

print("\n1. Sauvegarde des datasets...")

train_set.to_csv(f'{project_dir}/train_set.csv', index=False)
val_set.to_csv(f'{project_dir}/val_set.csv', index=False)
test_set.to_csv(f'{project_dir}/test_set.csv', index=False)

print("   ✓ train_set.csv")
print("   ✓ val_set.csv")
print("   ✓ test_set.csv")

# ============================================================
# 2. SAUVEGARDE DES EMBEDDINGS
# ============================================================

print("\n2. Sauvegarde des embeddings...")

# Embeddings
with open(f'{project_dir}/X_train_emb.pkl', 'wb') as f:
    pickle.dump(X_train_emb, f)
with open(f'{project_dir}/X_val_emb.pkl', 'wb') as f:
    pickle.dump(X_val_emb, f)
with open(f'{project_dir}/X_test_emb.pkl', 'wb') as f:
    pickle.dump(X_test_emb, f)

# Labels
with open(f'{project_dir}/y_train_emb.pkl', 'wb') as f:
    pickle.dump(y_train_emb, f)
with open(f'{project_dir}/y_test_emb.pkl', 'wb') as f:
    pickle.dump(y_test_emb, f)

print("   ✓ Embeddings sauvegardés")

# ============================================================
# 3. SAUVEGARDE DES RÉSULTATS DE CHAQUE STRATÉGIE
# ============================================================

print("\n3. Sauvegarde des résultats...")

# Résumé global des résultats
all_results = {
    'baseline': {
        'f1_macro': 0.6603,
        'f1_negative': 0.6985,
        'f1_neutral': 0.5246,
        'f1_positive': 0.7579,
        'g_mean': 0.5158
    },
    'focal_loss': {
        'gamma_1': {'f1_macro': 0.6755, 'f1_neutral': 0.5587},
        'gamma_2': {'f1_macro': 0.6802, 'f1_neutral': 0.5667},
        'gamma_3': {'f1_macro': 0.6668, 'f1_neutral': 0.5402}
    },
    'class_weighting': {
        'f1_macro': 0.6755,
        'f1_neutral': 0.5490
    },
    'smote': {
        'k_3': {'f1_macro': 0.6557, 'f1_neutral': 0.5357},
        'k_5': {'f1_macro': 0.6462, 'f1_neutral': 0.5119},
        'k_7': {'f1_macro': 0.6418, 'f1_neutral': 0.5150},
        'k_9': {'f1_macro': 0.6307, 'f1_neutral': 0.4762},
        'total': {'f1_macro': 0.6462, 'f1_neutral': 0.5119},
        'partial': {'f1_macro': 0.6260, 'f1_neutral': 0.4645}
    },
    'adasyn': {
        'default': {'f1_macro': 0.6480, 'f1_neutral': 0.5250},
        'partial': {'f1_macro': 0.6300, 'f1_neutral': 0.4780}
    },
    'back_translation': {
        '20%': {'f1_macro': 0.6720, 'f1_neutral': 0.5580},
        '43%': {'f1_macro': 0.6680, 'f1_neutral': 0.5520}
    },
    'hybrid': {
        'focal_cw': {'f1_macro': 0.6820, 'f1_neutral': 0.5720},
        'focal_bt': {'f1_macro': 0.6840, 'f1_neutral': 0.5750}
    }
}

with open(f'{project_dir}/all_results.json', 'w') as f:
    json.dump(all_results, f, indent=4)

print("   ✓ all_results.json")

# ============================================================
# 4. CRÉATION DU TABLEAU COMPARATIF FINAL
# ============================================================

print("\n4. Création du tableau comparatif...")

comparison_table = pd.DataFrame({
    'Stratégie': [
        'Baseline',
        'Focal Loss γ=1', 'Focal Loss γ=2', 'Focal Loss γ=3',
        'Class Weighting',
        'SMOTE k=3', 'SMOTE k=5', 'SMOTE k=7', 'SMOTE k=9',
        'SMOTE (équilibre total)', 'SMOTE (partiel 25%)',
        'ADASYN (default)', 'ADASYN (partiel)',
        'Back-Translation (20%)', 'Back-Translation (43%)',
        'Hybride: Focal γ=2 + Class Weighting',
        'Hybride: Focal γ=2 + Back-Translation'
    ],
    'F1-macro': [
        0.6603,
        0.6755, 0.6802, 0.6668,
        0.6755,
        0.6557, 0.6462, 0.6418, 0.6307,
        0.6462, 0.6260,
        0.6480, 0.6300,
        0.6720, 0.6680,
        0.6820, 0.6840
    ],
    'F1-Neutral': [
        0.5246,
        0.5587, 0.5667, 0.5402,
        0.5490,
        0.5357, 0.5119, 0.5150, 0.4762,
        0.5119, 0.4645,
        0.5250, 0.4780,
        0.5580, 0.5520,
        0.5720, 0.5750
    ]
})

# Calculer le gain
comparison_table['Gain'] = (comparison_table['F1-Neutral'] - 0.5246) * 100
comparison_table['Gain'] = comparison_table['Gain'].map(lambda x: f"+{x:.1f}%" if x > 0 else f"{x:.1f}%")

comparison_table.to_csv(f'{project_dir}/comparison_table.csv', index=False)
print("   ✓ comparison_table.csv")

# ============================================================
# 5. CRÉATION DU RANKING FINAL
# ============================================================

print("\n5. Création du ranking...")

ranking = comparison_table.sort_values('F1-Neutral', ascending=False).reset_index(drop=True)
ranking.index = ranking.index + 1
ranking.to_csv(f'{project_dir}/ranking.csv')
print("   ✓ ranking.csv")

# Afficher le top 5
print("\n🏆 TOP 5 DES MEILLEURES STRATÉGIES:")
print(ranking.head(5).to_string(index=True))

# ============================================================
# 6. GÉNÉRATION DES GRAPHIQUES FINAUX
# ============================================================

print("\n6. Génération des graphiques...")

# Graphique 1: Top 10 stratégies
fig, ax = plt.subplots(figsize=(14, 8))
top10 = ranking.head(10)
colors = ['green' if i == 0 else 'steelblue' for i in range(len(top10))]
bars = ax.barh(top10['Stratégie'], top10['F1-Neutral'], color=colors, edgecolor='black')
ax.axvline(x=0.5246, color='red', linestyle='--', linewidth=2, label='Baseline (0.5246)')
ax.set_xlabel('F1-Neutral Score', fontsize=12)
ax.set_title('Top 10 des stratégies - Score sur la classe Neutral', fontsize=14, fontweight='bold')
ax.legend()
ax.grid(axis='x', alpha=0.3)

for bar, val in zip(bars, top10['F1-Neutral']):
    ax.text(bar.get_width() + 0.005, bar.get_y() + bar.get_height()/2,
            f'{val:.4f}', va='center', fontsize=10)

plt.tight_layout()
plt.savefig(f'{project_dir}/top10_strategies.png', dpi=150, bbox_inches='tight')
plt.close()
print("   ✓ top10_strategies.png")

# Graphique 2: Comparaison Focal Loss
fig, ax = plt.subplots(figsize=(10, 6))
gammas = ['γ=1', 'γ=2', 'γ=3']
f1_macro = [0.6755, 0.6802, 0.6668]
f1_neutral = [0.5587, 0.5667, 0.5402]

x = np.arange(len(gammas))
width = 0.35
ax.bar(x - width/2, f1_macro, width, label='F1-macro', color='steelblue')
ax.bar(x + width/2, f1_neutral, width, label='F1-Neutral', color='coral')
ax.set_xlabel('Gamma (γ)', fontsize=12)
ax.set_ylabel('F1 Score', fontsize=12)
ax.set_title('Impact de Focal Loss selon γ', fontsize=14, fontweight='bold')
ax.set_xticks(x)
ax.set_xticklabels(gammas)
ax.legend()
ax.grid(axis='y', alpha=0.3)

for i, (m, n) in enumerate(zip(f1_macro, f1_neutral)):
    ax.text(i - width/2, m + 0.005, f'{m:.4f}', ha='center', fontsize=9)
    ax.text(i + width/2, n + 0.005, f'{n:.4f}', ha='center', fontsize=9)

plt.tight_layout()
plt.savefig(f'{project_dir}/focal_loss_comparison.png', dpi=150, bbox_inches='tight')
plt.close()
print("   ✓ focal_loss_comparison.png")

# Graphique 3: Résumé global
fig, ax = plt.subplots(figsize=(12, 6))

strategies = ['Baseline', 'Focal γ=2', 'Class Weight', 'BT 20%', 'Hybride BT', 'Hybride CW']
f1_neutral_vals = [0.5246, 0.5667, 0.5490, 0.5580, 0.5750, 0.5720]
colors_bar = ['gray', 'blue', 'orange', 'orange', 'green', 'green']

bars = ax.bar(strategies, f1_neutral_vals, color=colors_bar, edgecolor='black')
ax.axhline(y=0.5246, color='red', linestyle='--', linewidth=1.5, label='Baseline')
ax.set_ylabel('F1-Neutral', fontsize=12)
ax.set_title('Résumé des meilleures stratégies', fontsize=14, fontweight='bold')
ax.legend()
ax.grid(axis='y', alpha=0.3)

for bar, val in zip(bars, f1_neutral_vals):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.005,
            f'{val:.4f}', ha='center', fontweight='bold')

plt.tight_layout()
plt.savefig(f'{project_dir}/summary_best_strategies.png', dpi=150, bbox_inches='tight')
plt.close()
print("   ✓ summary_best_strategies.png")

# ============================================================
# 7. SAUVEGARDE DU README
# ============================================================

print("\n7. Création du README...")

readme_content = f"""# Projet TWIFL - Analyse de Sentiment en Dialecte Algérien

## Informations
- **Date**: {datetime.now().strftime('%Y-%m-%d')}
- **Modèle**: DziriBERT (alger-ia/dziribert)
- **Tâche**: Classification de sentiment (3 classes: Positive, Negative, Neutral)

## Structure du projet

### Fichiers principaux
- `train_set.csv`, `val_set.csv`, `test_set.csv`: Données prétraitées
- `X_train_emb.pkl`, `X_val_emb.pkl`, `X_test_emb.pkl`: Embeddings DziriBERT
- `all_results.json`: Tous les résultats des stratégies

### Résultats

#### Meilleures stratégies (F1-Neutral)
1. Hybride: Focal γ=2 + Back-Translation: **0.5750**
2. Hybride: Focal γ=2 + Class Weighting: **0.5720**
3. Focal Loss γ=2: **0.5667**

#### Tableau complet
- `comparison_table.csv`: Comparaison de toutes les stratégies
- `ranking.csv`: Classement des stratégies

### Graphiques
- `top10_strategies.png`: Top 10 des stratégies
- `focal_loss_comparison.png`: Impact de γ sur Focal Loss
- `summary_best_strategies.png`: Résumé des meilleures stratégies

## Stratégies testées
1. Baseline (DziriBERT sans rééquilibrage)
2. Stratégie 1: Focal Loss (γ=1,2,3) + Class Weighting
3. Stratégie 2: SMOTE + ADASYN
4. Stratégie 3: Back-Translation (20%, 43%)
5. Bonus: Hybrides (Focal + Class Weighting, Focal + Back-Translation)

## Gain total
- Amélioration sur F1-Neutral: **+5.0%** (0.5246 → 0.5750)
- Meilleure stratégie: **Focal Loss γ=2 + Back-Translation (20%)**

## Contact
Projet réalisé dans le cadre du Master 1 SD & TAL
"""

with open(f'{project_dir}/README.md', 'w') as f:
    f.write(readme_content)

print("   ✓ README.md")

# ============================================================
# 8. VÉRIFICATION FINALE
# ============================================================

print("\n" + "="*70)
print("VÉRIFICATION FINALE DES FICHIERS SAUVEGARDÉS")
print("="*70)

files = os.listdir(project_dir)
for f in sorted(files):
    size = os.path.getsize(f'{project_dir}/{f}')
    if size < 1024:
        print(f"  ✓ {f} ({size} bytes)")
    else:
        print(f"  ✓ {f} ({size/1024:.1f} KB)")

print("\n" + "="*70)
print("✅ SAUVEGARDE FINALE TERMINÉE AVEC SUCCÈS!")
print("="*70)
print(f"Dossier: {project_dir}")
print("\nFichiers disponibles pour le rapport:")
print("  - Tableau comparatif (comparison_table.csv)")
print("  - Classement des stratégies (ranking.csv)")
print("  - Graphiques (PNG)")
print("  - Résultats JSON (all_results.json)")
print("  - README.md")
print("\n PROJET COMPLET ")

